[package]
name = "logregator"
version = "0.1.0"
edition = "2024"

[lib]
name = "logregator"

[[bin]]
name = "server"
bench=false
[[bin]]
name = "client"
bench=false
[[bin]]
name = "loadgen"
bench=false

[[bench]]
name = "codec_bench"
harness = false
[[bench]]
name = "engine_bench"
harness = false

[dependencies]
anyhow = "1.0.102"
tracing = { version = "0.1", features = ["attributes"] }
tokio = {version = "1.52.3", features = ["sync", "macros", "net", "io-util", "rt", "rt-multi-thread"]}
bytes = "1.10"
tokio-util = {version = "0.7", features = ["codec"]}
tokio-stream = "0.1.18"
futures = "0.3.32"
chrono = "0.4"
tracing-subscriber = "0.3.23"
clap = { version = "4.6.1", features = ["derive"] }
tracing-flame = "0.2.0"
rand = "0.10.1"
hdrhistogram = "7.5.4"
# metrics = "0.24.6"
# metrics-util = "0.20.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
owo-colors = "4.3.0"

[dev-dependencies]
tempfile = "3.27.0"
criterion = {version = "0.8.2", features = ["html_reports"]}
