[package]
name = "logregator-net"
version = "0.1.0"
edition = "2024"

[dependencies]
logregator-tsdb = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
nom = { workspace = true }
flume = { workspace = true }
tokio-util = { version = "0.7.19", features = ["codec"] }
tracing = { workspace = true }
thiserror = { workspace = true }
tokio-stream = "0.1.19"
futures = "0.3.34"

[dev-dependencies]
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }

